from docx import Document
from docx.shared import Inches
import io
import datetime
from utils.logger import logger

def generate_docx_report(image_buffer, prediction_label, confidence_score, confidence_percent, gradcam_buffer=None):
    """
    Generates a DOCX report for the thyroid cancer detection analysis.
    
    Args:
        image_buffer (BytesIO): The original image data.
        prediction_label (str): The predicted class label.
        confidence_score (float): The raw confidence score.
        confidence_percent (float): The confidence percentage.
        gradcam_buffer (BytesIO, optional): The Grad-CAM heatmap image data.
    
    Returns:
        BytesIO: buffer containing the DOCX file.
    """
    logger.info(f"Generating DOCX report for label: {prediction_label}")
    doc = Document()
    
    # Title
    doc.add_heading('Thyroid Cancer Detection Report', 0)
    
    # Date
    doc.add_paragraph(f"Date: {datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    
    # Analysis Section
    doc.add_heading('Analysis Results', level=1)
    
    p = doc.add_paragraph()
    p.add_run('Prediction: ').bold = True
    p.add_run(f"{prediction_label}\n")
    
    p.add_run('Confidence Score: ').bold = True
    p.add_run(f"{confidence_score:.4f}\n")
    
    p.add_run('Confidence Percentage: ').bold = True
    p.add_run(f"{confidence_percent:.2f}%")
    
    # Original Image
    doc.add_heading('Original Medical Image', level=1)
    if image_buffer:
        image_buffer.seek(0)
        doc.add_picture(image_buffer, width=Inches(4.0))
        
    # Grad-CAM Heatmap
    if gradcam_buffer:
        doc.add_heading('Grad-CAM Interpretability', level=1)
        doc.add_paragraph('The heatmap below visualizes the regions of the image that contributed most to the model\'s prediction.')
        gradcam_buffer.seek(0)
        doc.add_picture(gradcam_buffer, width=Inches(4.0))
    
    # Disclaimer
    doc.add_heading('Disclaimer', level=1)
    doc.add_paragraph(
        "This report is generated by an AI system (FibonacciNet) and is intended for assistive purposes only. "
        "It should not be used as a definitive medical diagnosis. Please consult a medical professional."
    )
    
    # Save to buffer
    doc_buffer = io.BytesIO()
    doc.save(doc_buffer)
    doc_buffer.seek(0)
    
    return doc_buffer
